import { Property, Trip, Review, Expense, Notification } from "@/types";

export const mockProperties: Property[] = [
  {
    id: "p1", hostId: "h1", hostName: "Priya Sharma", hostAvatar: "",
    title: "Oceanfront Villa with Infinity Pool",
    description: "Wake up to panoramic Arabian Sea views in this stunning 4-bedroom villa. Features a private infinity pool, outdoor dining area, and direct beach access. Perfect for groups seeking luxury in North Goa.",
    type: "villa",
    location: { address: "Anjuna Beach Road", city: "Goa", country: "India", lat: 15.5735, lng: 73.7422 },
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800", "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
    pricePerNight: 12500, maxGuests: 10, bedrooms: 4, bathrooms: 4, beds: 6,
    amenities: ["WiFi", "Pool", "AC", "Kitchen", "Parking", "Beach Access", "BBQ", "Garden"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: true },
    rating: 4.92, reviewCount: 128, isFeatured: true, isActive: true, createdAt: "2024-01-15"
  },
  {
    id: "p2", hostId: "h2", hostName: "Rajesh Kumar",
    title: "Cozy Mountain Cottage in Manali",
    description: "A charming wooden cottage nestled among pine trees with breathtaking Himalayan views. Fireplace, hot water, and a private balcony make this the perfect mountain retreat.",
    type: "cottage",
    location: { address: "Old Manali Road", city: "Manali", country: "India", lat: 32.2432, lng: 77.1892 },
    images: ["https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800", "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800"],
    pricePerNight: 4500, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 4,
    amenities: ["WiFi", "Fireplace", "Kitchen", "Mountain View", "Parking", "Heater"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.85, reviewCount: 89, isFeatured: true, isActive: true, createdAt: "2024-03-10"
  },
  {
    id: "p3", hostId: "h3", hostName: "Aarav Patel",
    title: "Heritage Haveli Suite in Jaipur",
    description: "Experience royal Rajasthani hospitality in this beautifully restored haveli. Hand-painted frescoes, courtyard dining, and rooftop views of Amber Fort.",
    type: "hotel",
    location: { address: "Amer Road", city: "Jaipur", country: "India", lat: 26.9855, lng: 75.8513 },
    images: ["https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800", "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800"],
    pricePerNight: 8000, maxGuests: 8, bedrooms: 4, bathrooms: 3, beds: 5,
    amenities: ["WiFi", "AC", "Restaurant", "Rooftop", "Heritage", "Room Service", "Courtyard"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.78, reviewCount: 203, isFeatured: true, isActive: true, createdAt: "2024-02-20"
  },
  {
    id: "p4", hostId: "h4", hostName: "Maya Nair",
    title: "Treehouse Resort by the Backwaters",
    description: "Unique treehouse stay overlooking Kerala backwaters. Includes kayaking, Ayurvedic spa access, and traditional Kerala cuisine. An unforgettable experience.",
    type: "resort",
    location: { address: "Kumarakom Lake", city: "Kerala", country: "India", lat: 9.6175, lng: 76.4301 },
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800", "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800"],
    pricePerNight: 15000, maxGuests: 4, bedrooms: 2, bathrooms: 2, beds: 2,
    amenities: ["WiFi", "Spa", "Pool", "Restaurant", "Kayaking", "Nature", "Room Service"],
    rules: { checkInTime: "15:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.95, reviewCount: 67, isFeatured: true, isActive: true, createdAt: "2024-04-05"
  },
  {
    id: "p5", hostId: "h5", hostName: "Vikram Singh",
    title: "Riverside Camp with Rafting Access",
    description: "Adventure meets comfort at this riverside camp in Rishikesh. Luxury tents, bonfire area, and direct access to white-water rafting. Ideal for adventure groups.",
    type: "hostel",
    location: { address: "Shivpuri Road", city: "Rishikesh", country: "India", lat: 30.1162, lng: 78.3115 },
    images: ["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800", "https://images.unsplash.com/photo-1537905569824-f89f14cceb68?w=800"],
    pricePerNight: 2500, maxGuests: 12, bedrooms: 6, bathrooms: 4, beds: 12,
    amenities: ["WiFi", "Bonfire", "Rafting", "Meals Included", "Parking", "River View"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.7, reviewCount: 156, isFeatured: false, isActive: true, createdAt: "2024-05-12"
  },
  {
    id: "p6", hostId: "h6", hostName: "Ananya Reddy",
    title: "Lake Palace Suite in Udaipur",
    description: "Luxurious suite with stunning Lake Pichola views. Features marble interiors, private butler service, and rooftop dining under the stars.",
    type: "hotel",
    location: { address: "Lake Palace Road", city: "Udaipur", country: "India", lat: 24.5764, lng: 73.6831 },
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800", "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800"],
    pricePerNight: 18000, maxGuests: 6, bedrooms: 3, bathrooms: 3, beds: 3,
    amenities: ["WiFi", "AC", "Lake View", "Butler", "Spa", "Restaurant", "Pool", "Gym"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.97, reviewCount: 312, isFeatured: true, isActive: true, createdAt: "2024-01-08"
  },
  {
    id: "p7", hostId: "h7", hostName: "Sophie Laurent",
    title: "French Colonial Villa in Pondicherry",
    description: "Beautiful French colonial-style villa in the White Town area. Walking distance to the beach, cafes, and the Aurobindo Ashram.",
    type: "villa",
    location: { address: "White Town", city: "Pondicherry", country: "India", lat: 11.9344, lng: 79.8300 },
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    pricePerNight: 7500, maxGuests: 8, bedrooms: 4, bathrooms: 3, beds: 5,
    amenities: ["WiFi", "AC", "Garden", "Kitchen", "Beach Nearby", "Courtyard", "Bicycle"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.82, reviewCount: 94, isFeatured: false, isActive: true, createdAt: "2024-06-01"
  },
  {
    id: "p8", hostId: "h8", hostName: "Deepak Menon",
    title: "Hilltop Bungalow in Ooty",
    description: "Colonial-era bungalow surrounded by tea gardens. Enjoy misty mornings, lush greenery, and the tranquility of the Nilgiri Hills.",
    type: "cottage",
    location: { address: "Elk Hill", city: "Ooty", country: "India", lat: 11.4102, lng: 76.6950 },
    images: ["https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800", "https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800"],
    pricePerNight: 5500, maxGuests: 8, bedrooms: 4, bathrooms: 2, beds: 5,
    amenities: ["WiFi", "Fireplace", "Garden", "Kitchen", "Parking", "Tea Garden View", "Heater"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.73, reviewCount: 71, isFeatured: false, isActive: true, createdAt: "2024-07-15"
  },
  {
    id: "p9", hostId: "h9", hostName: "Arjun Singh",
    title: "Premium Apartment in Mumbai Downtown",
    description: "Modern luxury apartment in BKC with floor-to-ceiling windows, overlooking the Arabian Sea. Perfect for groups visiting Mumbai.",
    type: "apartment",
    location: { address: "Bandra Kurla Complex", city: "Mumbai", country: "India", lat: 19.0760, lng: 72.8295 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 9500, maxGuests: 6, bedrooms: 2, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "AC", "Gym", "Parking", "City View", "Elevator", "Security"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.68, reviewCount: 142, isFeatured: false, isActive: true, createdAt: "2024-08-20"
  },
  {
    id: "p10", hostId: "h10", hostName: "Neha Patel",
    title: "Luxury Villa in Bangalore Tech Park",
    description: "Modern villa with smart home features, pool, and garden in Bangalore's premium tech hub.",
    type: "villa",
    location: { address: "Indiranagar", city: "Bangalore", country: "India", lat: 13.1939, lng: 77.6419 },
    images: ["https://images.unsplash.com/photo-1564078369132-bf2e4f129e5c?w=800"],
    pricePerNight: 11000, maxGuests: 8, bedrooms: 3, bathrooms: 3, beds: 4,
    amenities: ["WiFi", "Pool", "AC", "Kitchen", "Smart Home", "Parking", "Garden"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.72, reviewCount: 98, isFeatured: false, isActive: true, createdAt: "2024-06-15"
  },
  {
    id: "p11", hostId: "h11", hostName: "Rajiv Kapoor",
    title: "Beach Cottage in Alleppey Backwaters",
    description: "Charming beachfront cottage with boat access to Backwaters and traditional Kerala cuisine.",
    type: "cottage",
    location: { address: "Alleppey Beach Road", city: "Alleppey", country: "India", lat: 9.4981, lng: 76.3355 },
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"],
    pricePerNight: 4800, maxGuests: 5, bedrooms: 2, bathrooms: 2, beds: 2,
    amenities: ["WiFi", "Beach Access", "Kitchen", "Boat Access", "Garden", "AC"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.81, reviewCount: 112, isFeatured: false, isActive: true, createdAt: "2024-07-22"
  },
  {
    id: "p12", hostId: "h12", hostName: "Meera Sharma",
    title: "Desert Resort in Jaisalmer",
    description: "Authentic desert experience with camel rides, campfire, and traditional Rajasthani meals.",
    type: "resort",
    location: { address: "Desert Camp Road", city: "Jaisalmer", country: "India", lat: 26.8941, lng: 70.9142 },
    images: ["https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800"],
    pricePerNight: 3500, maxGuests: 10, bedrooms: 5, bathrooms: 3, beds: 10,
    amenities: ["WiFi", "Bonfire", "Camel Ride", "Traditional Meals", "Desert View", "Parking"],
    rules: { checkInTime: "14:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.76, reviewCount: 187, isFeatured: false, isActive: true, createdAt: "2024-05-18"
  },
  {
    id: "p13", hostId: "h13", hostName: "Vikram Patel",
    title: "Hilltop Resort in Himachal",
    description: "Scenic resort with adventure activities, trekking, and paragliding in Himachal Pradesh.",
    type: "resort",
    location: { address: "Kasauli Hill Road", city: "Kasauli", country: "India", lat: 30.8035, lng: 76.6542 },
    images: ["https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800"],
    pricePerNight: 5200, maxGuests: 12, bedrooms: 5, bathrooms: 4, beds: 8,
    amenities: ["WiFi", "Parking", "Adventure Activities", "Restaurant", "Mountain View", "Pool"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: true },
    rating: 4.83, reviewCount: 156, isFeatured: false, isActive: true, createdAt: "2024-04-10"
  },
  {
    id: "p14", hostId: "h14", hostName: "Priya Singh",
    title: "Modern Hostel in Delhi NCR",
    description: "Social hostel with common areas, co-working space, and perfect for backpackers and groups.",
    type: "hostel",
    location: { address: "Safdarjung Enclave", city: "Delhi", country: "India", lat: 28.5355, lng: 77.1884 },
    images: ["https://images.unsplash.com/photo-1555854877-bab0e5a737e7?w=800"],
    pricePerNight: 1800, maxGuests: 16, bedrooms: 8, bathrooms: 4, beds: 16,
    amenities: ["WiFi", "Kitchen", "Common Area", "Co-Working", "Games Room", "Parking"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.65, reviewCount: 234, isFeatured: false, isActive: true, createdAt: "2024-08-05"
  },
  {
    id: "p15", hostId: "h15", hostName: "Anushka Reddy",
    title: "Boutique Hotel in Lucknow",
    description: "Heritage boutique hotel combining Mughal architecture with modern amenities.",
    type: "hotel",
    location: { address: "Hazratganj", city: "Lucknow", country: "India", lat: 26.8407, lng: 80.9270 },
    images: ["https://images.unsplash.com/photo-1577720643272-265f434b3a09?w=800"],
    pricePerNight: 6500, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "AC", "Restaurant", "Heritage Design", "Courtyard", "WiFi"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.71, reviewCount: 127, isFeatured: false, isActive: true, createdAt: "2024-07-01"
  },
  {
    id: "p16", hostId: "h16", hostName: "Sanjay Kumar",
    title: "Beachfront Apartment in Kochin",
    description: "Stylish apartment facing the Arabian Sea with sunset views and close to Fort Kochin.",
    type: "apartment",
    location: { address: "Panampilly Nagar", city: "Kochin", country: "India", lat: 9.9689, lng: 76.3247 },
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"],
    pricePerNight: 7200, maxGuests: 5, bedrooms: 2, bathrooms: 2, beds: 2,
    amenities: ["WiFi", "Sea View", "AC", "Kitchen", "Balcony", "Parking"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.74, reviewCount: 89, isFeatured: false, isActive: true, createdAt: "2024-06-20"
  },
  {
    id: "p17", hostId: "h17", hostName: "Divya Nair",
    title: "Wellness Retreat in Kerala Backwaters",
    description: "Ayurvedic wellness center with yoga, spa treatments, and organic food in a serene setting.",
    type: "resort",
    location: { address: "Kumbalangi", city: "Kumbalangi", country: "India", lat: 10.0189, lng: 76.3022 },
    images: ["https://images.unsplash.com/photo-1596178065887-ba9ecf17dba9?w=800"],
    pricePerNight: 9800, maxGuests: 8, bedrooms: 4, bathrooms: 4, beds: 4,
    amenities: ["WiFi", "Yoga", "Spa", "Organic Food", "Meditation", "Nature"],
    rules: { checkInTime: "15:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.89, reviewCount: 203, isFeatured: true, isActive: true, createdAt: "2024-03-15"
  },
  {
    id: "p18", hostId: "h18", hostName: "Rohan Mishra",
    title: "Budget Apartment in Hyderabad",
    description: "Affordable and comfortable apartment in Hi-Tech City for backpackers and budget travelers.",
    type: "apartment",
    location: { address: "HITEC City", city: "Hyderabad", country: "India", lat: 17.3613, lng: 78.3733 },
    images: ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800"],
    pricePerNight: 2200, maxGuests: 3, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "AC", "Kitchen", "Parking", "Hot Water", "Security"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.58, reviewCount: 178, isFeatured: false, isActive: true, createdAt: "2024-09-01"
  },
  {
    id: "p19", hostId: "h19", hostName: "Kavya Gupta",
    title: "Houseboat in Backwaters",
    description: "Traditional Kerala houseboat with crew, kitchen, and all amenities for a unique backwater cruise.",
    type: "villa",
    location: { address: "Vembanad Lake", city: "Vembanad", country: "India", lat: 9.6300, lng: 76.4100 },
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800"],
    pricePerNight: 16000, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "Kitchen", "Crew Included", "Scenic View", "Fishing", "Dining"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.91, reviewCount: 145, isFeatured: true, isActive: true, createdAt: "2024-02-28"
  },
  {
    id: "p20", hostId: "h20", hostName: "Nikhil Sharma",
    title: "Adventure Camp in Ladakh",
    description: "Luxury adventure camp with trekking, rock climbing, and mountaineering in Ladakh.",
    type: "resort",
    location: { address: "Leh valley", city: "Leh", country: "India", lat: 34.2268, lng: 77.5619 },
    images: ["https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800"],
    pricePerNight: 8500, maxGuests: 10, bedrooms: 5, bathrooms: 4, beds: 8,
    amenities: ["WiFi", "Adventure Activities", "Meals", "Mountain View", "Parking", "Guide"],
    rules: { checkInTime: "13:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.84, reviewCount: 192, isFeatured: false, isActive: true, createdAt: "2024-05-25"
  },
  {
    id: "p21", hostId: "h21", hostName: "Shreya Iyer",
    title: "Luxury Hotel in Pune",
    description: "Five-star hotel with world-class amenities, conference rooms, and fine dining.",
    type: "hotel",
    location: { address: "Camp", city: "Pune", country: "India", lat: 18.5204, lng: 73.8567 },
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    pricePerNight: 10500, maxGuests: 4, bedrooms: 2, bathrooms: 2, beds: 2,
    amenities: ["WiFi", "Gym", "Pool", "Restaurant", "Spa", "Concierge"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.79, reviewCount: 256, isFeatured: false, isActive: true, createdAt: "2024-08-10"
  },
  {
    id: "p22", hostId: "h22", hostName: "Amitesh Singh",
    title: "Forest Cottage in Coorg",
    description: "Secluded cottage surrounded by coffee plantations and forests in Coorg.",
    type: "cottage",
    location: { address: "Madikeri", city: "Coorg", country: "India", lat: 12.4191, lng: 75.7339 },
    images: ["https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800"],
    pricePerNight: 4200, maxGuests: 4, bedrooms: 2, bathrooms: 1, beds: 2,
    amenities: ["WiFi", "Kitchen", "Forest View", "Fireplace", "Parking", "Garden"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.77, reviewCount: 103, isFeatured: false, isActive: true, createdAt: "2024-07-08"
  },
  {
    id: "p23", hostId: "h23", hostName: "Isha Verma",
    title: "Modern Studio in Bangalore",
    description: "Contemporary studio apartment in upscale Bangalore neighborhood with all modern amenities.",
    type: "apartment",
    location: { address: "Whitefield", city: "Bangalore", country: "India", lat: 13.0016, lng: 77.7210 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 3800, maxGuests: 2, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "AC", "Parking", "Gym", "Security", "Laundry"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.61, reviewCount: 145, isFeatured: false, isActive: true, createdAt: "2024-09-05"
  },
  {
    id: "p24", hostId: "h24", hostName: "Harshit Patel",
    title: "Riverside Camping Resort in Rishikesh",
    description: "Adventure camping with activities like rafting, yoga, and meditation in Rishikesh.",
    type: "resort",
    location: { address: "Muni Ki Reti", city: "Rishikesh", country: "India", lat: 30.0836, lng: 78.2676 },
    images: ["https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800"],
    pricePerNight: 2800, maxGuests: 15, bedrooms: 6, bathrooms: 3, beds: 15,
    amenities: ["WiFi", "Camping", "Rafting", "Yoga", "Meals", "Bonfire"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.69, reviewCount: 267, isFeatured: false, isActive: true, createdAt: "2024-06-12"
  },
  {
    id: "p25", hostId: "h25", hostName: "Sandhya Rao",
    title: "Heritage Fort Hotel in Jodhpur",
    description: "Historic fort converted into a boutique hotel with traditional decor and rooftop restaurant.",
    type: "hotel",
    location: { address: "Jodhpur Fort Area", city: "Jodhpur", country: "India", lat: 26.2389, lng: 73.0243 },
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800"],
    pricePerNight: 8800, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "AC", "Restaurant", "Rooftop", "Heritage", "Fort View"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.82, reviewCount: 198, isFeatured: false, isActive: true, createdAt: "2024-04-20"
  },
  {
    id: "p26", hostId: "h26", hostName: "Ravi Patel",
    title: "Beachfront Villa in Goa (South)",
    description: "Spacious beachfront villa in South Goa with private beach access and luxury amenities.",
    type: "villa",
    location: { address: "Palolem Beach", city: "Palolem", country: "India", lat: 14.9412, lng: 73.7706 },
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800"],
    pricePerNight: 13500, maxGuests: 8, bedrooms: 4, bathrooms: 3, beds: 5,
    amenities: ["WiFi", "Beach Access", "Pool", "Kitchen", "Parking", "Garden"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: true },
    rating: 4.88, reviewCount: 167, isFeatured: true, isActive: true, createdAt: "2024-01-30"
  },
  {
    id: "p27", hostId: "h27", hostName: "Chandni Sharma",
    title: "Budget Hostel in Jaipur Backpacker Area",
    description: "Vibrant hostel with rooftop terrace, kitchen access, and social events.",
    type: "hostel",
    location: { address: "MI Road", city: "Jaipur", country: "India", lat: 26.9124, lng: 75.8262 },
    images: ["https://images.unsplash.com/photo-1555854877-bab0e5a737e7?w=800"],
    pricePerNight: 1500, maxGuests: 20, bedrooms: 10, bathrooms: 5, beds: 20,
    amenities: ["WiFi", "Kitchen", "Rooftop", "Common Area", "Games", "Safe"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.55, reviewCount: 312, isFeatured: false, isActive: true, createdAt: "2024-08-18"
  },
  {
    id: "p28", hostId: "h28", hostName: "Vikram Desai",
    title: "Luxury Apartment in Chennai",
    description: "High-rise apartment with modern interiors and panoramic city views.",
    type: "apartment",
    location: { address: "Marina Beach Area", city: "Chennai", country: "India", lat: 13.0499, lng: 80.2624 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 6800, maxGuests: 4, bedrooms: 2, bathrooms: 2, beds: 2,
    amenities: ["WiFi", "AC", "City View", "Gym", "Parking", "Security"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.67, reviewCount: 134, isFeatured: false, isActive: true, createdAt: "2024-07-25"
  },
  {
    id: "p29", hostId: "h29", hostName: "Pooja Nair",
    title: "Mountain Resort in Dalhousie",
    description: "Picturesque resort nestled in Himalayas with trekking trails and scenic views.",
    type: "resort",
    location: { address: "Dalhousie", city: "Dalhousie", country: "India", lat: 32.5410, lng: 75.9410 },
    images: ["https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800"],
    pricePerNight: 4900, maxGuests: 10, bedrooms: 5, bathrooms: 3, beds: 7,
    amenities: ["WiFi", "Mountain View", "Trekking", "Restaurant", "Parking", "Fireplace"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.75, reviewCount: 156, isFeatured: false, isActive: true, createdAt: "2024-06-08"
  },
  {
    id: "p30", hostId: "h30", hostName: "Ashok Singh",
    title: "Budget Hotel in Agra",
    description: "Affordable hotel near Taj Mahal with clean rooms and helpful staff.",
    type: "hotel",
    location: { address: "Near Taj Mahal", city: "Agra", country: "India", lat: 27.1751, lng: 78.0421 },
    images: ["https://images.unsplash.com/photo-1577720643272-265f434b3a09?w=800"],
    pricePerNight: 2500, maxGuests: 3, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "AC", "Room Service", "Restaurant", "Located Near Taj Mahal", "Parking"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.52, reviewCount: 289, isFeatured: false, isActive: true, createdAt: "2024-09-10"
  },
  {
    id: "p31", hostId: "h31", hostName: "Nisha Kumar",
    title: "Garden Villa in Mysore",
    description: "Beautiful villa surrounded by gardens in the city of palaces.",
    type: "villa",
    location: { address: "Mysore Palace Area", city: "Mysore", country: "India", lat: 12.2958, lng: 76.6394 },
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"],
    pricePerNight: 7800, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "Garden", "AC", "Kitchen", "Parking", "Palace View"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.70, reviewCount: 98, isFeatured: false, isActive: true, createdAt: "2024-08-02"
  },
  {
    id: "p32", hostId: "h32", hostName: "Deepak Verma",
    title: "Beachside Hostel in Varkala",
    description: "Beachfront hostel with cliff views and social atmosphere in Varkala, Kerala.",
    type: "hostel",
    location: { address: "Varkala Cliff", city: "Varkala", country: "India", lat: 8.7394, lng: 76.7277 },
    images: ["https://images.unsplash.com/photo-1555854877-bab0e5a737e7?w=800"],
    pricePerNight: 1900, maxGuests: 18, bedrooms: 8, bathrooms: 4, beds: 18,
    amenities: ["WiFi", "Beach Access", "Kitchen", "Rooftop", "Sea View", "Cafe"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.64, reviewCount: 203, isFeatured: false, isActive: true, createdAt: "2024-07-14"
  },
  {
    id: "p33", hostId: "h33", hostName: "Ritika Rao",
    title: "Luxury Suite in Bangalore Five-Star",
    description: "Premium suite in a luxury five-star hotel with butler service and spa.",
    type: "hotel",
    location: { address: "Koramangala", city: "Bangalore", country: "India", lat: 12.9352, lng: 77.6245 },
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    pricePerNight: 11500, maxGuests: 3, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "Spa", "Room Service", "Butler", "Fine Dining", "Gym"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.85, reviewCount: 234, isFeatured: false, isActive: true, createdAt: "2024-05-18"
  },
  {
    id: "p34", hostId: "h34", hostName: "Samrat Patel",
    title: "Farmhouse in Punjab",
    description: "Traditional Punjabi farmhouse with farm-to-table dining and countryside experience.",
    type: "villa",
    location: { address: "near Chandigarh", city: "Chandigarh", country: "India", lat: 30.7333, lng: 76.7794 },
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"],
    pricePerNight: 5600, maxGuests: 10, bedrooms: 5, bathrooms: 3, beds: 6,
    amenities: ["WiFi", "Farm", "Kitchen", "Parking", "Garden", "Countryside View"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: true },
    rating: 4.73, reviewCount: 112, isFeatured: false, isActive: true, createdAt: "2024-06-25"
  },
  {
    id: "p35", hostId: "h35", hostName: "Snehal Iyer",
    title: "Penthouse in Mumbai Marine Drive",
    description: "Stunning penthouse with 360-degree city views and Queen's Necklace view.",
    type: "apartment",
    location: { address: "Marine Drive", city: "Mumbai", country: "India", lat: 18.9676, lng: 72.8191 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 15500, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "City View", "AC", "Gym", "Security", "Parking"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.91, reviewCount: 156, isFeatured: true, isActive: true, createdAt: "2024-02-14"
  },
  {
    id: "p36", hostId: "h36", hostName: "Anish Kumar",
    title: "Eco-Resort in Gulmarg",
    description: "Sustainable eco-resort with nature activities and organic farm in Gulmarg.",
    type: "resort",
    location: { address: "Gulmarg Valley", city: "Gulmarg", country: "India", lat: 34.4039, lng: 75.4168 },
    images: ["https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800"],
    pricePerNight: 6200, maxGuests: 12, bedrooms: 6, bathrooms: 4, beds: 8,
    amenities: ["WiFi", "Eco-Friendly", "Organic Food", "Nature Hikes", "Parking", "Garden"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.80, reviewCount: 145, isFeatured: false, isActive: true, createdAt: "2024-04-28"
  },
  {
    id: "p37", hostId: "h37", hostName: "Garima Singh",
    title: "Heritage Hotel in Varanasi",
    description: "Historic hotel overlooking the Ganges River with spiritual atmosphere.",
    type: "hotel",
    location: { address: "Ghat Area", city: "Varanasi", country: "India", lat: 25.3201, lng: 82.9854 },
    images: ["https://images.unsplash.com/photo-1577720643272-265f434b3a09?w=800"],
    pricePerNight: 5400, maxGuests: 4, bedrooms: 2, bathrooms: 1, beds: 2,
    amenities: ["WiFi", "River View", "AC", "Restaurant", "Ghat View", "Spiritual"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.68, reviewCount: 176, isFeatured: false, isActive: true, createdAt: "2024-07-30"
  },
  {
    id: "p38", hostId: "h38", hostName: "Vivek Patel",
    title: "Beachfront Cottage in Anjuna",
    description: "Cozy beachfront cottage in Anjuna with yoga deck and beach access.",
    type: "cottage",
    location: { address: "Anjuna Beach", city: "Anjuna", country: "India", lat: 15.5769, lng: 73.7505 },
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"],
    pricePerNight: 6900, maxGuests: 4, bedrooms: 2, bathrooms: 1, beds: 2,
    amenities: ["WiFi", "Beach Access", "Yoga Deck", "Kitchen", "Garden", "Sea View"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.72, reviewCount: 128, isFeatured: false, isActive: true, createdAt: "2024-08-12"
  },
  {
    id: "p39", hostId: "h39", hostName: "Simran Sharma",
    title: "Modern Loft in Delhi",
    description: "Trendy loft apartment in central Delhi with rooftop garden.",
    type: "apartment",
    location: { address: "Hauz Khas", city: "Delhi", country: "India", lat: 28.5244, lng: 77.2015 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 5300, maxGuests: 3, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "Loft Design", "Rooftop Garden", "AC", "Kitchen", "Parking"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.63, reviewCount: 167, isFeatured: false, isActive: true, createdAt: "2024-09-08"
  },
  {
    id: "p40", hostId: "h40", hostName: "Aryan Desai",
    title: "Adventure Resort in Shimla",
    description: "Thrilling adventure resort with zip-lining, rock climbing, and paragliding.",
    type: "resort",
    location: { address: "Mall Road Area", city: "Shimla", country: "India", lat: 31.7745, lng: 77.1745 },
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
    pricePerNight: 7100, maxGuests: 14, bedrooms: 7, bathrooms: 4, beds: 10,
    amenities: ["WiFi", "Adventure Activities", "Zip-line", "Rock Climbing", "Paragliding", "Meals"],
    rules: { checkInTime: "13:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.77, reviewCount: 189, isFeatured: false, isActive: true, createdAt: "2024-05-22"
  },
  {
    id: "p41", hostId: "h41", hostName: "Neetu Singh",
    title: "Budget Apartment in Kolkata",
    description: "Cozy apartment in cultural hub of Kolkata with local charm.",
    type: "apartment",
    location: { address: "Park Circus", city: "Kolkata", country: "India", lat: 22.5448, lng: 88.3426 },
    images: ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800"],
    pricePerNight: 2800, maxGuests: 2, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "AC", "Local Area", "Kitchen", "Easy Access", "Safe"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.56, reviewCount: 142, isFeatured: false, isActive: true, createdAt: "2024-09-12"
  },
  {
    id: "p42", hostId: "h42", hostName: "Pradeep Kumar",
    title: "Riverside Villa in Tehri",
    description: "Serene riverside villa with water sports and nature trails.",
    type: "villa",
    location: { address: "Tehri Dam Area", city: "Tehri", country: "India", lat: 30.3760, lng: 78.4804 },
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"],
    pricePerNight: 6500, maxGuests: 8, bedrooms: 4, bathrooms: 2, beds: 4,
    amenities: ["WiFi", "River View", "Water Sports", "Kitchen", "Parking", "Nature Trails"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.71, reviewCount: 105, isFeatured: false, isActive: true, createdAt: "2024-08-20"
  },
  {
    id: "p43", hostId: "h43", hostName: "Isha Desai",
    title: "Boutique Hotel in Rajkot",
    description: "Charming boutique hotel with personalized service in Rajkot.",
    type: "hotel",
    location: { address: "Rajkot Central", city: "Rajkot", country: "India", lat: 22.3039, lng: 70.7928 },
    images: ["https://images.unsplash.com/photo-1577720643272-265f434b3a09?w=800"],
    pricePerNight: 4300, maxGuests: 4, bedrooms: 2, bathrooms: 1, beds: 2,
    amenities: ["WiFi", "AC", "Restaurant", "Personalized Service", "Parking", "Central Location"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.60, reviewCount: 89, isFeatured: false, isActive: true, createdAt: "2024-07-15"
  },
  {
    id: "p44", hostId: "h44", hostName: "Sameer Patel",
    title: "Premium Hostel in Mumbai Backpackers",
    description: "Social hostel with rooftop bar and tours in central Mumbai.",
    type: "hostel",
    location: { address: "Colaba", city: "Mumbai", country: "India", lat: 18.9620, lng: 72.8347 },
    images: ["https://images.unsplash.com/photo-1555854877-bab0e5a737e7?w=800"],
    pricePerNight: 2100, maxGuests: 22, bedrooms: 10, bathrooms: 5, beds: 22,
    amenities: ["WiFi", "Rooftop Bar", "Kitchen", "Tours", "Social Events", "Laundry"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.62, reviewCount: 287, isFeatured: false, isActive: true, createdAt: "2024-08-25"
  },
  {
    id: "p45", hostId: "h45", hostName: "Tanya Kumar",
    title: "Luxury Resort in Maldah",
    description: "All-inclusive luxury resort with water games and luxury accommodations.",
    type: "resort",
    location: { address: "Maldah Lakeside", city: "Maldah", country: "India", lat: 25.0108, lng: 88.1395 },
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
    pricePerNight: 12000, maxGuests: 10, bedrooms: 5, bathrooms: 5, beds: 5,
    amenities: ["WiFi", "Water Games", "Luxury", "All-Inclusive", "Pool", "Restaurant"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.78, reviewCount: 167, isFeatured: false, isActive: true, createdAt: "2024-03-30"
  },
  {
    id: "p46", hostId: "h46", hostName: "Harsh Singh",
    title: "Cottage in Mussoorie",
    description: "Peaceful cottage in the hills with nature and adventure activities.",
    type: "cottage",
    location: { address: "Mussoorie Hills", city: "Mussoorie", country: "India", lat: 30.4610, lng: 78.0710 },
    images: ["https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800"],
    pricePerNight: 4700, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "Hill View", "Nature", "Adventure", "Fireplace", "Kitchen"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.74, reviewCount: 124, isFeatured: false, isActive: true, createdAt: "2024-06-18"
  },
  {
    id: "p47", hostId: "h47", hostName: "Lavanya Nair",
    title: "Modern Apartment in Thiruvananthapuram",
    description: "Contemporary apartment in God's Own Country with sea proximity.",
    type: "apartment",
    location: { address: "Kazakkoottam", city: "Thiruvananthapuram", country: "India", lat: 8.5241, lng: 76.9366 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 4100, maxGuests: 3, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "AC", "Modern", "Safe Area", "Nearby Sea", "Parking"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.59, reviewCount: 110, isFeatured: false, isActive: true, createdAt: "2024-09-15"
  },
  {
    id: "p48", hostId: "h48", hostName: "Rakesh Verma",
    title: "Safari Resort in Jim Corbett",
    description: "Jungle resort with tiger safari and wildlife tours in Jim Corbett.",
    type: "resort",
    location: { address: "Jim Corbett Park", city: "Ramnagar", country: "India", lat: 29.8589, lng: 79.3789 },
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
    pricePerNight: 8200, maxGuests: 12, bedrooms: 6, bathrooms: 4, beds: 8,
    amenities: ["WiFi", "Safari Tours", "Jungle View", "Restaurant", "Parking", "Naturalist"],
    rules: { checkInTime: "14:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.81, reviewCount: 201, isFeatured: false, isActive: true, createdAt: "2024-05-08"
  },
  {
    id: "p49", hostId: "h49", hostName: "Shruti Patel",
    title: "Budget Hotel in Vadodara",
    description: "Clean and comfortable budget hotel in vibrant Vadodara.",
    type: "hotel",
    location: { address: "Sayajiganj", city: "Vadodara", country: "India", lat: 22.3072, lng: 73.1812 },
    images: ["https://images.unsplash.com/photo-1577720643272-265f434b3a09?w=800"],
    pricePerNight: 2700, maxGuests: 2, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "AC", "Room Service", "Restaurant", "Budget Friendly", "Central Area"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.53, reviewCount: 156, isFeatured: false, isActive: true, createdAt: "2024-08-28"
  },
  {
    id: "p50", hostId: "h50", hostName: "Arun Kumar",
    title: "Lakeside Villa in Lonavala",
    description: "Romantic lakeside villa with sunset views and water activities.",
    type: "villa",
    location: { address: "Lonavala Lake", city: "Lonavala", country: "India", lat: 18.7528, lng: 73.4047 },
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"],
    pricePerNight: 8900, maxGuests: 6, bedrooms: 3, bathrooms: 2, beds: 3,
    amenities: ["WiFi", "Lake View", "Water Activities", "Garden", "Sunset View", "Kitchen"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.76, reviewCount: 139, isFeatured: false, isActive: true, createdAt: "2024-04-14"
  },
  {
    id: "p51", hostId: "h51", hostName: "Meena Sharma",
    title: "Backpacker Haven in Goa",
    description: "Social hostel with parties, beach access, and international crowd.",
    type: "hostel",
    location: { address: "Baga Beach", city: "Baga", country: "India", lat: 15.5890, lng: 73.7476 },
    images: ["https://images.unsplash.com/photo-1555854877-bab0e5a737e7?w=800"],
    pricePerNight: 1600, maxGuests: 25, bedrooms: 12, bathrooms: 6, beds: 25,
    amenities: ["WiFi", "Beach Access", "Kitchen", "Rooftop Party", "Social Events", "Safe"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.61, reviewCount: 356, isFeatured: false, isActive: true, createdAt: "2024-07-05"
  },
  {
    id: "p52", hostId: "h52", hostName: "Vikram Sharma",
    title: "Premium Suite in Delhi Five-Star",
    description: "Luxurious suite with world-class amenities in New Delhi.",
    type: "hotel",
    location: { address: "Connaught Place", city: "Delhi", country: "India", lat: 28.6328, lng: 77.1892 },
    images: ["https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800"],
    pricePerNight: 13000, maxGuests: 3, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "Luxury", "Spa", "Fine Dining", "Concierge", "City View"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.88, reviewCount: 267, isFeatured: true, isActive: true, createdAt: "2024-01-25"
  },
  {
    id: "p53", hostId: "h53", hostName: "Divya Verma",
    title: "Cottage in Kodaikanal",
    description: "Quaint cottage on the misty hills of Kodaikanal with lake view.",
    type: "cottage",
    location: { address: "Kodaikanal Lake", city: "Kodaikanal", country: "India", lat: 10.2381, lng: 77.4892 },
    images: ["https://images.unsplash.com/photo-1605146769289-440113cc3d00?w=800"],
    pricePerNight: 5300, maxGuests: 5, bedrooms: 2, bathrooms: 2, beds: 2,
    amenities: ["WiFi", "Lake View", "Fireplace", "Kitchen", "Mountain View", "Garden"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.73, reviewCount: 118, isFeatured: false, isActive: true, createdAt: "2024-08-08"
  },
  {
    id: "p54", hostId: "h54", hostName: "Siddharth Singh",
    title: "Budget Apartment in Ahmedabad",
    description: "Affordable apartment in business district with good connectivity.",
    type: "apartment",
    location: { address: "Navrangpura", city: "Ahmedabad", country: "India", lat: 23.1815, lng: 72.6369 },
    images: ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800"],
    pricePerNight: 2400, maxGuests: 2, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "AC", "Safe Area", "Near Metro", "Parking", "Kitchen"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.54, reviewCount: 134, isFeatured: false, isActive: true, createdAt: "2024-09-20"
  },
  {
    id: "p55", hostId: "h55", hostName: "Ishita Nair",
    title: "Village Resort in Kumaon",
    description: "Traditional village resort with organic farming and local culture experience.",
    type: "resort",
    location: { address: "Kumaon Region", city: "Almora", country: "India", lat: 29.5941, lng: 79.6419 },
    images: ["https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800"],
    pricePerNight: 3200, maxGuests: 10, bedrooms: 5, bathrooms: 3, beds: 7,
    amenities: ["WiFi", "Organic Farm", "Local Culture", "Nature", "Parking", "Restaurant"],
    rules: { checkInTime: "13:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.67, reviewCount: 145, isFeatured: false, isActive: true, createdAt: "2024-06-30"
  },
  {
    id: "p56", hostId: "h56", hostName: "Arjun Nair",
    title: "Heritage Resort in Chettinad",
    description: "Palatial heritage mansion hotel with traditional Tamil architecture.",
    type: "hotel",
    location: { address: "Chettinad Region", city: "Karaikudi", country: "India", lat: 10.4670, lng: 78.1360 },
    images: ["https://images.unsplash.com/photo-1577720643272-265f434b3a09?w=800"],
    pricePerNight: 7300, maxGuests: 8, bedrooms: 4, bathrooms: 2, beds: 4,
    amenities: ["WiFi", "Heritage", "AC", "Restaurant", "Courtyard", "Traditional"],
    rules: { checkInTime: "14:00", checkOutTime: "12:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.79, reviewCount: 167, isFeatured: false, isActive: true, createdAt: "2024-05-12"
  },
  {
    id: "p57", hostId: "h57", hostName: "Neha Desai",
    title: "Beachfront Apartment in Diu",
    description: "Sweet beachfront apartment with Portuguese architecture charm.",
    type: "apartment",
    location: { address: "Diu Island", city: "Diu", country: "India", lat: 20.7439, lng: 70.9876 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 4900, maxGuests: 4, bedrooms: 2, bathrooms: 1, beds: 2,
    amenities: ["WiFi", "Beach View", "AC", "Portuguese Design", "Parking", "Sea Access"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: true, partiesAllowed: false },
    rating: 4.70, reviewCount: 95, isFeatured: false, isActive: true, createdAt: "2024-08-15"
  },
  {
    id: "p58", hostId: "h58", hostName: "Rishi Kumar",
    title: "Adventure Hostel in Rishikesh",
    description: "Backpacker-friendly hostel with rafting packages and yoga classes.",
    type: "hostel",
    location: { address: "Rishikesh Main", city: "Rishikesh", country: "India", lat: 30.0856, lng: 78.2674 },
    images: ["https://images.unsplash.com/photo-1555854877-bab0e5a737e7?w=800"],
    pricePerNight: 1400, maxGuests: 20, bedrooms: 9, bathrooms: 4, beds: 20,
    amenities: ["WiFi", "Rafting Package", "Yoga Classes", "Kitchen", "Social Area", "River"],
    rules: { checkInTime: "12:00", checkOutTime: "10:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: true },
    rating: 4.63, reviewCount: 298, isFeatured: false, isActive: true, createdAt: "2024-07-20"
  },
  {
    id: "p59", hostId: "h59", hostName: "Swati Sharma",
    title: "Luxury Water Villa in Backwaters",
    description: "Ultra-premium floating villa on Kerala Backwaters with private pool.",
    type: "villa",
    location: { address: "Luxury Backwaters Zone", city: "Alleppey", country: "India", lat: 9.4800, lng: 76.3200 },
    images: ["https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800"],
    pricePerNight: 22000, maxGuests: 6, bedrooms: 3, bathrooms: 3, beds: 3,
    amenities: ["WiFi", "Private Pool", "Water Villa", "Chef", "Luxury", "24/7 Service"],
    rules: { checkInTime: "15:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.97, reviewCount: 89, isFeatured: true, isActive: true, createdAt: "2024-01-10"
  },
  {
    id: "p60", hostId: "h60", hostName: "Nandini Patel",
    title: "Modern Studio in Bangalore Tech Zone",
    description: "Contemporary co-living space in Bangalore's startup hub.",
    type: "apartment",
    location: { address: "Sarjapur Road", city: "Bangalore", country: "India", lat: 12.8597, lng: 77.6788 },
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    pricePerNight: 3500, maxGuests: 1, bedrooms: 1, bathrooms: 1, beds: 1,
    amenities: ["WiFi", "Co-working", "Modern", "Gym", "Parking", "Tech Zone"],
    rules: { checkInTime: "14:00", checkOutTime: "11:00", smokingAllowed: false, petsAllowed: false, partiesAllowed: false },
    rating: 4.65, reviewCount: 178, isFeatured: false, isActive: true, createdAt: "2024-09-18"
  },
];

export const mockTrips: Trip[] = [
  {
    id: "t1", title: "Goa Beach Getaway 🏖️", destination: "Goa", country: "India",
    checkIn: "2025-05-01", checkOut: "2025-05-05", nights: 4,
    groupSize: 6, budgetPerPerson: 15000, currency: "INR",
    createdBy: "u1",
    members: [
      { userId: "u1", name: "You", email: "you@example.com", role: "organizer", joinedAt: "2025-03-01", totalContributed: 8500, avatar: "" },
      { userId: "u2", name: "Amit Verma", email: "amit@example.com", role: "member", joinedAt: "2025-03-02", totalContributed: 5200 },
      { userId: "u3", name: "Sneha Iyer", email: "sneha@example.com", role: "member", joinedAt: "2025-03-02", totalContributed: 6800 },
      { userId: "u4", name: "Rohan Das", email: "rohan@example.com", role: "member", joinedAt: "2025-03-03", totalContributed: 3500 },
    ],
    status: "active", inviteCode: "GOA2025X", totalExpenses: 24000, createdAt: "2025-03-01"
  },
  {
    id: "t2", title: "Manali Snow Trek ❄️", destination: "Manali", country: "India",
    checkIn: "2025-06-15", checkOut: "2025-06-20", nights: 5,
    groupSize: 4, budgetPerPerson: 12000, currency: "INR",
    createdBy: "u1",
    members: [
      { userId: "u1", name: "You", email: "you@example.com", role: "organizer", joinedAt: "2025-04-01", totalContributed: 0 },
      { userId: "u5", name: "Kavya Nair", email: "kavya@example.com", role: "member", joinedAt: "2025-04-02", totalContributed: 0 },
    ],
    status: "planning", inviteCode: "MNLI2025", totalExpenses: 0, createdAt: "2025-04-01"
  },
  {
    id: "t3", title: "Rajasthan Royal Tour 🏰", destination: "Jaipur", country: "India",
    checkIn: "2024-12-20", checkOut: "2024-12-25", nights: 5,
    groupSize: 8, budgetPerPerson: 20000, currency: "INR",
    createdBy: "u1",
    members: [
      { userId: "u1", name: "You", email: "you@example.com", role: "organizer", joinedAt: "2024-11-01", totalContributed: 18500 },
      { userId: "u2", name: "Amit Verma", email: "amit@example.com", role: "member", joinedAt: "2024-11-01", totalContributed: 17200 },
      { userId: "u3", name: "Sneha Iyer", email: "sneha@example.com", role: "member", joinedAt: "2024-11-02", totalContributed: 19800 },
      { userId: "u6", name: "Priya Menon", email: "priya@example.com", role: "member", joinedAt: "2024-11-03", totalContributed: 16500 },
      { userId: "u7", name: "Arjun Kapoor", email: "arjun@example.com", role: "member", joinedAt: "2024-11-03", totalContributed: 15200 },
    ],
    status: "completed", inviteCode: "JPR2024", totalExpenses: 87200, createdAt: "2024-11-01",
    finalizedProperty: mockProperties[2]
  },
];

export const mockExpenses: Expense[] = [
  { id: "e1", tripId: "t1", description: "Beach Shack Dinner", amount: 4500, currency: "INR", category: "food", paidBy: "u1", paidByName: "You", splitAmong: ["u1", "u2", "u3", "u4"], createdAt: "2025-05-01" },
  { id: "e2", tripId: "t1", description: "Scooter Rental (2 days)", amount: 1200, currency: "INR", category: "transport", paidBy: "u2", paidByName: "Amit Verma", splitAmong: ["u1", "u2", "u3", "u4"], createdAt: "2025-05-01" },
  { id: "e3", tripId: "t1", description: "Dudhsagar Falls Trip", amount: 6000, currency: "INR", category: "activity", paidBy: "u3", paidByName: "Sneha Iyer", splitAmong: ["u1", "u2", "u3", "u4"], createdAt: "2025-05-02" },
  { id: "e4", tripId: "t1", description: "Groceries & Drinks", amount: 3200, currency: "INR", category: "food", paidBy: "u1", paidByName: "You", splitAmong: ["u1", "u2", "u3", "u4"], createdAt: "2025-05-02" },
  { id: "e5", tripId: "t1", description: "Night Market Shopping", amount: 2800, currency: "INR", category: "shopping", paidBy: "u4", paidByName: "Rohan Das", splitAmong: ["u1", "u2", "u3", "u4"], createdAt: "2025-05-03" },
  { id: "e6", tripId: "t1", description: "Villa Booking (4 nights)", amount: 50000, currency: "INR", category: "accommodation", paidBy: "u1", paidByName: "You", splitAmong: ["u1", "u2", "u3", "u4"], createdAt: "2025-04-28" },
];

export const mockReviews: Review[] = [
  {
    id: "r1", propertyId: "p1", bookingId: "b1", guestId: "u2", guestName: "Amit Verma",
    hostId: "h1", rating: 5, comment: "Absolutely stunning villa! The infinity pool overlooking the sea was a highlight. Our group of 6 had the best time. Priya was an amazing host.",
    categories: { cleanliness: 5, accuracy: 5, communication: 5, location: 5, checkin: 4, value: 5 },
    hostReply: "Thank you Amit! So glad your group enjoyed the stay. Come back anytime! 🌊",
    createdAt: "2025-01-20"
  },
  {
    id: "r2", propertyId: "p1", bookingId: "b2", guestId: "u3", guestName: "Sneha Iyer",
    hostId: "h1", rating: 4, comment: "Great location and beautiful property. The pool was perfect. Only minor issue was WiFi being slow at times.",
    categories: { cleanliness: 5, accuracy: 4, communication: 5, location: 5, checkin: 4, value: 4 },
    createdAt: "2025-02-15"
  },
];

export const mockNotifications: Notification[] = [
  { id: "n1", userId: "u1", tripId: "t1", type: "expense", message: "Amit added an expense: Scooter Rental (₹1,200)", link: "/trips/t1", isRead: false, createdAt: "2025-05-01T10:30:00" },
  { id: "n2", userId: "u1", tripId: "t1", type: "member", message: "Rohan Das joined your Goa trip!", link: "/trips/t1", isRead: false, createdAt: "2025-04-28T14:00:00" },
  { id: "n3", userId: "u1", type: "booking", message: "Your booking at Oceanfront Villa is confirmed!", link: "/bookings", isRead: true, createdAt: "2025-04-27T09:00:00" },
  { id: "n4", userId: "u1", tripId: "t1", type: "vote", message: "Sneha voted 👍 for Oceanfront Villa", link: "/trips/t1", isRead: true, createdAt: "2025-04-25T16:00:00" },
  { id: "n5", userId: "u1", type: "system", message: "Welcome to SplitsVilla! Start planning your first trip.", isRead: true, createdAt: "2025-03-01T00:00:00" },
];

export const categoryIcons = [
  { key: "villas", label: "Villas", icon: "🏡" },
  { key: "beach", label: "Beach", icon: "🏖️" },
  { key: "mountains", label: "Mountains", icon: "⛰️" },
  { key: "trending", label: "Trending", icon: "🔥" },
  { key: "city", label: "City Center", icon: "🏙️" },
  { key: "budget", label: "Budget Stays", icon: "💰" },
  { key: "luxury", label: "Luxury", icon: "👑" },
  { key: "pools", label: "Pools", icon: "🏊" },
  { key: "countryside", label: "Countryside", icon: "🌿" },
  { key: "new", label: "New Listings", icon: "✨" },
];
